# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Matthew Remmel
title: Principal Software & Security Consultant
email: matt@remmel.dev
website: https://remmel.dev

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: mattremmel
github_username: mattremmel
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: mattremmel
linkedin_username: matthewremmel
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: TODO
# googleplus_username: +jekyll
orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
#   - title: itsgoingto.be
#     icon: fas fa-globe
#     url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.png
about_content: | # this will include new lines to allow paragraphs
  I’m a Principal Software & Security Consultant with a strong background in both secure systems and end-to-end software engineering. I help organizations design, build, and protect modern applications and infrastructure, combining hands-on development experience with deep security expertise. Whether it’s architecting scalable backend systems, auditing code for vulnerabilities, or shaping security policies, I partner closely with clients to deliver practical, reliable solutions.

content:
  #   - title: Projects # Title for the section
  #     layout: list # Type of content section (list/text)
  #     content:
  #       - layout: top-middle
  #         title: Super awesome project
  #         link: github.com/sproogen
  #         # link_text: Project Website
  #         additional_links:
  #           - title: sproogen/modern-resume-theme
  #             icon: fab fa-github
  #             url: github.com/sproogen/modern-resume-theme
  #           # - title:  Github page for project (eg. sproogen/modern-resume-theme)
  #           #   icon: fab fa-github
  #           #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
  #         quote: >
  #           This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
  #         description: | # this will include new lines to allow paragraphs
  #           I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Bell Rock, Inc
        link: https://bellrock.cc
        link_text: bellrock.cc
        sub_title: Principal Software & Security Consultant
        caption: May 2023 - Present
        description: | # this will include new lines to allow paragraphs
          - Provided strategic technical guidance on architecture, security posture, and product scalability.
          - Delivered end-to-end software solutions—including backend systems, web applications, and APIs—using modern frameworks and cloud platforms.
          - Conducted security audits and risk assessments across infrastructure, codebases, and vendors; translated findings into actionable policies and procedures aligned with SOC 2, ISO 27001, and PCI DSS.

      - layout: left
        title: Tesouro HQ, Inc
        link: https://tesouro.com
        link_text: tesouro.com
        sub_title: Founding Engineer
        caption: Aug 2021 - Jun 2025
        description: | # this will include new lines to allow paragraphs
          - Served as the founding engineer and technical advisor, collaborating with founders, vendors, and financial institutions to lead initial engineering effort, and to shape product direction and go-to-market strategy.
          - Spearheaded backend development in C\#/ .NET, orchestrating distributed microservices on AWS to power merchant onboarding, transaction processing, event-driven billing/funding, and compliance workflows.
          - Led architecture and implementation efforts that enabled SOC 2 Type II and PCI DSS Level 1 certification, building a secure, auditable foundation for sensitive payment data.
          - Scaled infrastructure and real-time systems with Kafka, Cassandra, PostgreSQL, and Kubernetes, supporting high-throughput payments and accelerating adoption by partner banks and platforms.

      - layout: left
        title: E-gineering, LLC
        link: https://e-gineering.com
        link_text: e-gineering.com
        sub_title: Senior Software Engineer
        caption: Jul 2019 - Feb 2022
        description: | # this will include new lines to allow paragraphs
          - Developed and maintained microservices for a high-volume customer loyalty platform using Java and Kotlin on GCP with Kubernetes.
          - Built scalable, event-driven systems with Kafka, supporting asynchronous service interactions and real-time reward processing for millions of users.
          - Collaborated with cross-functional teams to deliver new loyalty features and enhance user experience.
          - Strengthened observability and system reliability through improved telemetry and alerting infrastructure.

      - layout: left
        title: E-gineering, LLC
        link: https://e-gineering.com
        link_text: e-gineering.com
        sub_title: iOS Engineer
        caption: May 2015 - Jul 2019
        description: | # this will include new lines to allow paragraphs
          - Designed and built internal iOS applications from the ground up, aligning with business goals and meeting HIPAA and FDA compliance standards.
          - Modernized legacy Objective-C apps by migrating key functionality to Swift, improving performance, code clarity, automated testing, and long-term maintainability.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Indiana University
        caption: 2016 - 2017
        sub_title: Master of Science in Computer Science, Information Security

      - layout: top-middle
        title: Indiana University
        caption: 2013 - 2016
        sub_title: Bachelor of Science in Computer Science

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag
